const actionTypes = {
  LOAD_ITEMS_LIST: 'LOAD_ITEMS_LIST',
  LOAD_ITEMS_LIST_ERROR: 'LOAD_ITEMS_LIST_ERROR',
  LOAD_ITEM: 'LOAD_ITEM',
  LOAD_ITEM_ERROR: 'LOAD_ITEM_ERROR',
  LOAD_SHOPPING_CART: 'LOAD_SHOPPING_CART',
  LOAD_SHOPPING_CART_ERROR: 'LOAD_SHOPPING_CART_ERROR',
  PUT_ITEM_IN_CART: 'PUT_ITEM_IN_CART',
  PUT_ITEM_IN_CART_ERROR: 'PUT_ITEM_IN_CART_ERROR',
  DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
  DELETE_ITEM_FROM_CART_ERROR: 'DELETE_ITEM_FROM_CART_ERROR',
  FILTER_ITEMS: 'FILTER_ITEMS',
  FILTER_ITEMS_ERROR: 'FILTER_ITEMS_ERROR',
};

export default actionTypes;
